<?xml version="1.0"?>
<robot name="two_steering" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
<xacro:property name="PI" value="3.1415926535897931"/>

<xacro:property name="radius" value=".4"/>
<xacro:property name="L" value="1."/>
<xacro:property name="thickness" value="0.02"/>
   
<material name="color">
    <color rgba="1 0 0 1"/>
</material>
  
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>

  <link name="base_link">
    <visual>
      <origin rpy="0 ${PI/2} 0" xyz="${L/2} 0 0"/>
      <geometry>
        <cylinder length="${L}" radius="0.05"/>
      </geometry>
      <material name="color"/>
    </visual>
  </link>
  
  <link name="footprint"/>
  
  <joint name="footprint" type="fixed">
      <child link="base_link"/>
      <parent link="footprint"/>
    <origin xyz="0 0 ${radius}"/>
   </joint>
   
   
<xacro:macro name="wheel" params="name offset">
    
<link name="${name}_wheel">
    <visual>
      <geometry>
        <cylinder length="${thickness}" radius="${radius}"/>
      </geometry>
      <material name="black"/>
    </visual>
    
    <visual>
        <geometry>
            <box size="${thickness} ${1.9*radius} ${1.1*thickness}"/>
        </geometry>
      <material name="white"/>
    </visual> 
    <visual>
        <geometry>
            <box size="${1.9*radius} ${thickness} ${1.1*thickness}"/>
        </geometry>
      <material name="white"/>
    </visual>             
</link>

<link name="${name}_wheel_steering"/>

<joint name="${name}_wheel_steering" type="revolute">
    <parent link="base_link"/>
    <child link="${name}_wheel_steering"/>
    <origin xyz="${offset} 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="${-PI/4}" upper="${PI/4}" effort="0" velocity="100"/>
</joint>

<joint name="${name}_wheel" type="continuous">
    <parent link="${name}_wheel_steering"/>
    <child link="${name}_wheel"/>
    <origin rpy="${-PI/2} 0 0"/>
    <axis xyz="0 0 1"/>
</joint>    
</xacro:macro>

 <xacro:wheel name="front" offset="${L}"/>
 <xacro:wheel name="rear" offset="0"/>
 
  
</robot>
